---
- hosts: test
  vars_files:
    - vault.yml
  tasks:
  - name: Same as above but subscribe to a specific pool by ID.
    redhat_subscription:
      state: present
      username: "{{username}}"
      password: "{{password}}"
      pool_ids: 8a85f9815bb07800015bb08404d71143
  - name: Disable all repositories except rhel-7-server-rpms
    rhsm_repository:
      name: '*'
      state: disabled
  - name: Enable all repositories starting with rhel-7-server
    rhsm_repository:
      name: rhel-7-server-rpms
      state: enabled
  - name: Enable all repositories starting with rhel-gluster
    rhsm_repository:
      name: rh-gluster-3-for-rhel-7-server-rpms
      state: enabled
  - name: System update
    yum:
      name: '*'
      state: latest
# need to add reboot
  - name: install redhat storage server
    yum:
      name:  redhat-storage-server
      state: latest
# need to add reboot
  - name: Restart service firewalld and enabled, in all cases
    service:
      name: firewalld
      state: restarted
      enabled: yes 
  - name: Restart service gluster and enabled, in all cases
    service:
      name: glusterd
      state: restarted
      enabled: yes
  - firewalld:
      service: glusterfs
      permanent: true
      state: enabled
  - firewalld:
      port: 5667/tcp
      permanent: true
      state: enabled
  - name: Reload firewalld
    command: "firewall-cmd --reload"
