---
- hosts: ansi_g
  vars_files:
    - vault.yml
  tasks:
  - name: Same as above but subscribe to a specific pool by ID.
    redhat_subscription:
      state: present
      username: "{{username}}"
      password: "{{password}}"
      pool_ids: 8a85f9815bb07800015bb08404d71143
  - name: Disable all repositories except rhel-7-server-rpms
    rhsm_repository:
      name: '*'
      state: disabled
  - name: Enable all repositories starting with rhel-7-server
    rhsm_repository:
      name: rhel-7-server-rpms
      state: enabled
  - name: Enable all repositories starting with rhel-gluster
    rhsm_repository:
      name: rh-gluster-3-for-rhel-7-server-rpms
      state: enabled
  - name: System update
    yum:
      name: '*'
      state: latest
# need to add reboot
  - name: Reboot system
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
  - name: Wait for system to become reachable
    wait_for_connection:
      delay: 5
      timeout: 300
      connect_timeout: 20
  - name: install redhat storage server
    yum:
      name:  redhat-storage-server
      state: latest
# need to add reboot
  - name: Reboot system
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
  - name: Wait for system to become reachable
    wait_for_connection:
      delay: 5
      timeout: 300
      connect_timeout: 20
  - name: Restart service firewalld and enabled, in all cases
    service:
      name: firewalld
      state: restarted
      enabled: yes 
  - name: Restart service gluster and enabled, in all cases
    service:
      name: glusterd
      state: restarted
      enabled: yes
  - firewalld:
      service: glusterfs
      permanent: true
      state: enabled
  - firewalld:
      port: 5667/tcp
      permanent: true
      state: enabled
  - name: Reload firewalld
    command: "firewall-cmd --reload"
# Disk 
  - name: Create a PV disk 
    lvg:
      pvs: /dev/sdb
      vg: vg1
  - name: create Thinkpool
    lvol:
      vg: vg1
      thinpool: lvpool
      size: 5g
  - name: Create lvm
    lvol:
      vg: vg1
      lv: lv1
      thinpool: lvpool
      size: 1g
  - name: Create a exf filesystem on lv1
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv1
#  - name: Create Dir Brick
#    file:
#      path: /brick
#      state: 
#      mode: 0755
  - name: mount 
    mount:
      path: /mnt/brick
      src: /dev/vg1/lv1
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
  - name: Create dir inside mnt point
    file:
      path: /mnt/brick/brick1
      state: directory
      mode: 0775
